version: '3.3'



networks:
  prom-mon:

services:

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert.rules:/etc/prometheus/alert.rules
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.enable-admin-api' #allow admin api and reload
      - '--log.level=debug' #for troubleshooting
    ports:
      - 9090:9090
    networks:
      - prom-mon
    restart: always

  pushgateway:
    image: prom/pushgateway
    ports:
      - 9091:9091
    networks:
      - prom-mon
    restart: always

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
      - mariadb
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning/dashboards/:/etc/grafana/provisioning/dashboards/
      - ./grafana/provisioning/datasources/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
    env_file:
      - ./grafana/config.monitoring
    networks:
      - prom-mon
    restart: always

  alertmanager:
    image: prom/alertmanager:v0.15.0-rc.3
    depends_on:
      - mailhog
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/config.yml:/etc/alertmanager/config.yml
    networks:
      - prom-mon
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'
#      - '--cluster.peer=alertmanager2:9094'

#  alertmanager2:
#    image: prom/alertmanager:v0.15.0-rc.3
#    ports:
#      - 9094:9093
#    configs:
#      - source: config.yml
#        target: /etc/alertmanager/config.yml
#    networks:
#      - prom-mon
#    restart: always
#    command:
#      - '--config.file=/etc/alertmanager/config.yml'
#      - '--storage.path=/alertmanager'
#      - '--cluster.peer=alertmanager:9094'

  cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 9095:9095
    networks:
      - prom-mon
    restart: always
    command:
      - '--port=9095'

  mariadb:
     image: mariadb
     environment:
         - MYSQL_ROOT_PASSWORD=mariadb
         - MYSQL_DATABASE=grafana
     networks:
      - prom-mon

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - prom-mon
    restart: always