{
 "title": "Spring Boot 2.0 Metrics",
 "description": "Spring Boot 2.0 Metrics Dashboard",
 "tags": [
  "java",
  "spring-boot",
  "spring-boot-2",
  "micrometer"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "App Namespace", "query": "label_values(app_namespace)" },
   { "name": "app_name", "label": "App Name", "query": "label_values(app_name)" }
  ]
 },
 "panels": [
  { "title": "Uptime Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Process Uptime",
   "type": "singlestat",
   "description": "The uptime of the Java virtual machine",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "format": "dtdurations",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_uptime_seconds{app_name=\"$app_name\"}"
    }
   ]
  },
  {
   "title": "Process Start Time",
   "type": "singlestat",
   "description": "The starttime of the Java virtual machine",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "format": "dateTimeAsUS",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_starttime_seconds{app_name=\"$app_name\"} * 1000"
    }
   ]
  },
  {
   "title": "CPU Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Processor Count",
     "type": "singlestat",
     "description": "The number of processors available to the Java virtual machine",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 2 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "system_cpu_count{app_name=~\"$app_name\"}"
      }
     ]
    },
    {
     "title": "CPU Usage",
     "type": "graph",
     "description": "The sum of the number of runnable entities queued to available processors and the number of runnable entities running on the available processors averaged over a period of time",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 2 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "process_cpu_usage{app_name=~\"$app_name\"}",
       "legendFormat": "{{app_name}} - process"
      },
      {
       "expr": "system_cpu_usage{app_name=~\"$app_name\"} ",
       "legendFormat": "{{app_name}} - system"
      }
     ]
    }
   ]
  },
  {
   "title": "Logback Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Warn Events",
     "type": "singlestat",
     "description": "Number of warn level events that made it to the logs",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "logback_events_total{app_name=~\"$app_name\", level=\"warn\"}"
      }
     ]
    },
    {
     "title": "Debug Events",
     "type": "singlestat",
     "description": "Number of debug level events that made it to the logs",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "logback_events_total{app_name=~\"$app_name\", level=\"debug\"}"
      }
     ]
    },
    {
     "title": "Error Events",
     "type": "singlestat",
     "description": "Number of error level events that made it to the logs",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "logback_events_total{app_name=~\"$app_name\", level=\"error\"}"
      }
     ]
    },
    {
     "title": "Trace Events",
     "type": "singlestat",
     "description": "Number of trace level events that made it to the logs",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 3 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "logback_events_total{app_name=~\"$app_name\", level=\"trace\"}"
      }
     ]
    },
    {
     "title": "Info Events",
     "type": "singlestat",
     "description": "Number of info level events that made it to the logs",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "logback_events_total{app_name=~\"$app_name\", level=\"info\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Thread Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Threads Peak",
     "type": "graph",
     "description": "The peak live thread count since the Java virtual machine started or peak was reset",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_peak{app_name=~\"$app_name\"}",
       "legendFormat": "{{app_name}}"
      }
     ]
    },
    {
     "title": "Live Daemon Threads",
     "type": "graph",
     "description": "The current number of live daemon threads",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_daemon{app_name=~\"$app_name\"}",
       "legendFormat": "{{app_name}}"
      }
     ]
    },
    {
     "title": "Live Total Threads",
     "type": "graph",
     "description": "The current number of live threads including both daemon and non-daemon threads",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_threads_live{app_name=~\"$app_name\"}",
       "legendFormat": "{{app_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Buffer Count",
     "type": "graph",
     "description": "An estimate of the number of buffers in the pool",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_count{app_name=~\"$app_name\"}",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Buffer Mem Used",
     "type": "graph",
     "description": "An estimate of the memory that the Java virtual machine is using for this buffer pool",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_memory_used_bytes{app_name=~\"$app_name\"}",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Buffer Capacity",
     "type": "graph",
     "description": "An estimate of the total capacity of the buffers in this pool",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_buffer_total_capacity_bytes{app_name=~\"$app_name\"}",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Max Memory",
     "type": "graph",
     "description": "The maximum amount of memory in bytes that can be used for memory management",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_max_bytes{app_name=~\"$app_name\"}",
       "legendFormat": "{{id}} ({{area}})"
      }
     ]
    },
    {
     "title": "Used Memory",
     "type": "graph",
     "description": "The amount of used memory",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_used_bytes{app_name=~\"$app_name\"}",
       "legendFormat": "{{id}} ({{area}})"
      }
     ]
    },
    {
     "title": "Committed Memory",
     "type": "graph",
     "description": "The amount of memory in bytes that is committed for  the Java virtual machine to use",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_committed_bytes{app_name=~\"$app_name\"}",
       "legendFormat": "{{id}} ({{area}})"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Garbage Collection Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Max Data Size",
     "type": "graph",
     "description": "Max size of old generation memory pool",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_max_data_size_bytes{app_name=~\"$app_name\"}",
       "legendFormat": "{{app_name}}"
      }
     ]
    },
    {
     "title": "Live Data Size",
     "type": "graph",
     "description": "Size of old generation memory pool after a full GC",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_live_data_size_bytes{app_name=~\"$app_name\"}",
       "legendFormat": "{{app_name}}"
      }
     ]
    },
    {
     "title": "Promotion Rate",
     "type": "graph",
     "description": "Count of positive increases in the size of the old generation memory pool before GC to after GC",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_promotion_rate_total{app_name=~\"$app_name\"}",
       "legendFormat": "{{app_name}}"
      }
     ]
    },
    {
     "title": "Allocation Rate",
     "type": "graph",
     "description": "Incremented for an increase in the size of the young generation memory pool after one GC to before the next",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_allocation_rate_total{app_name=~\"$app_name\"}",
       "legendFormat": "{{app_name}}"
      }
     ]
    },
    {
     "title": "Pause Count",
     "type": "graph",
     "description": "Time spent in GC pause",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_pause_seconds_count{app_name=~\"$app_name\"}",
       "legendFormat": "{{cause}} ({{action}})"
      }
     ]
    },
    {
     "title": "Pause Duration",
     "type": "graph",
     "description": "Time spent in GC pause",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_pause_seconds_sum{app_name=~\"$app_name\"}",
       "legendFormat": "{{cause}} ({{action}})"
      }
     ]
    }
   ]
  },
  {
   "title": "Class Loader Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Classes Loaded",
     "type": "graph",
     "description": "The number of classes that are currently loaded in the Java virtual machine",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_classes_loaded{app_name=~\"$app_name\"}",
       "legendFormat": "{{app_name}}"
      }
     ]
    },
    {
     "title": "Classes Unloaded",
     "type": "graph",
     "description": "The total number of classes unloaded since the Java virtual machine has started execution",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "jvm_classes_unloaded_total{app_name=~\"$app_name\"}",
       "legendFormat": "{{app_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Server Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Requests Rate",
     "type": "graph",
     "description": "Count of servlet requests",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(http_server_requests_seconds_count{app_name=~\"$app_name\"}[$__interval])",
       "legendFormat": "{{method}} {{uri}} - {{status}}"
      }
     ]
    },
    {
     "title": "HTTP Requests Time",
     "type": "graph",
     "description": "Timer of servlet requests",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "http_server_requests_seconds_max{app_name=~\"$app_name\"}",
       "legendFormat": "{{method}} {{uri}} - {{status}}"
      }
     ]
    }
   ]
  }
 ]
}